name: backends

networks:
  macvlan_lan:
    external: true
    name: ${NET_NAME}

services:
  node1:
    image: nginx:alpine
    container_name: node1
    networks:
      macvlan_lan:
        ipv4_address: ${NODE1_IP}
    volumes:
      - ./sites/node1:/usr/share/nginx/html:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

  node2:
    image: nginx:alpine
    container_name: node2
    networks:
      macvlan_lan:
        ipv4_address: ${NODE2_IP}
    volumes:
      - ./sites/node2:/usr/share/nginx/html:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
